# Generated by Django 5.2.7 on 2025-11-04 15:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Το τηλέφωνο πρέπει να περιέχει 8–15 ψηφία και μπορεί να ξεκινά με +.', regex='^\\+?\\d{8,15}$')])),
                ('specialization', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=10, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
