# Generated by Django 5.2.7 on 2025-11-04 15:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Διάρκεια σε λεπτά (15–240).', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)])),
                ('status', models.CharField(choices=[('SCHEDULED', 'Προγραμματισμένη'), ('COMPLETED', 'Ολοκληρώθηκε'), ('CANCELED', 'Ακυρώθηκε'), ('NO_SHOW', 'Δεν εμφανίστηκε')], db_index=True, default='SCHEDULED', max_length=12)),
                ('session_type', models.CharField(choices=[('IN_PERSON', 'Δια ζώσης'), ('ONLINE', 'Διαδικτυακά')], db_index=True, default='IN_PERSON', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes_from_therapist', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='accounts.psychologist')),
            ],
            options={
                'ordering': ['-session_datetime'],
                'indexes': [models.Index(fields=['psychologist', 'session_datetime'], name='appointment_psychol_db78c4_idx'), models.Index(fields=['patient', 'session_datetime'], name='appointment_patient_7601f5_idx'), models.Index(fields=['status', 'session_type'], name='appointment_status_635fb9_idx')],
            },
        ),
    ]
