# Generated by Django 5.2.7 on 2025-11-04 15:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(db_index=True, max_length=35)),
                ('mental_disorder', models.CharField(blank=True, max_length=25, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Το τηλέφωνο πρέπει να περιέχει 8–15 ψηφία και μπορεί να ξεκινά με +.', regex='^\\+?\\d{8,15}$')])),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('emergency_contact_name', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Το τηλέφωνο πρέπει να περιέχει 8–15 ψηφία και μπορεί να ξεκινά με +.', regex='^\\+?\\d{8,15}$')])),
                ('status', models.CharField(choices=[('ACTIVE', 'Ενεργός'), ('INACTIVE', 'Aνενεργός')], db_index=True, default='ACTIVE', max_length=10)),
                ('first_session_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='accounts.psychologist')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('goals', models.CharField(blank=True, max_length=35, null=True)),
                ('next_steps', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='patients.patient')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='accounts.psychologist')),
            ],
            options={
                'ordering': ['patient', '-is_active', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['psychologist', 'status', 'last_name'], name='patients_pa_psychol_690fca_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('psychologist', 'email'), name='uq_patient_email_per_psych'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('psychologist', 'phone_number'), name='uq_patient_phone_per_psych'),
        ),
    ]
